### ISSUE TITLE
SAM dependency in errorrates.py

### ISSUE THREAD

**Issue by andreas-wilm** [isovic/samscripts#3]
Hi,

while errorrates.py is a super handy script, it does not support reading from BAM neither from stdin, which would be very handy for large BAM files. 

Andreas

**Comment by isovic** [comment]
Hey!
How about I add support for piping input in, so you can feed it with output from samtools view and do a BAM->SAM conversion from the outside?

**Comment by andreas-wilm** [comment]
Yes sure. It looks like the code partially supports this. Was too lazy to fix it myself. Sorry lah

**Comment by isovic** [comment]
No worries :)
It will have to wait a bit though, not very high on the priority list...
I'll leave this open.

**Comment by andreas-wilm** [comment]
Fixed with 0b7dc1b3936b2cd8424decdc445f23d4695b32f8
