### ISSUE TITLE
Wrong read length reported

### ISSUE THREAD

**Issue by andreas-wilm** [isovic/samscripts#5]
I got a BAM file with Pacbio reads aligned against an E.coli genome and errorrates.py reports the following lengths

```
Read length:            882690.71       687608.33       701700.00       50000.00        4227900.00
```

which is clearly not possible. The correct values are:

```
$ samtools view my.bam | awk '{print length($10)}' | datamash mean 1 sstdev 1 min 1 max  1
8873.2  6918.1  500 42279
```

which roughly matches the details analysis output:

```
$ cut -f 11 analysis-error_rate/my.bam-error_rates-base.csv | datamash mean 1 sstdev 1 min 1 max  1
8825.6  6872.9  500 42279
```

So something weird must happens to these values after they get parsed from the csv file

Andreas

**Comment by isovic** [comment]
Fixed in commit: f6986374458fe30cd43c516dfde98eae91cd5658
There was literally a factor of 100x for the read lengths (I added a factor of 100x to the output of match and error rates to convert them to percentages, and I accidentally placed the multiplication in the line with read lengths as well).
